site_name: Experts Certification
site_description: FIWARE Experts Certification
docs_dir: doc/
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_neutral.css"]
repo_url: https://github.com/Fiware/expert-certification
google_analytics: ['UA-80297547-1', 'fiware-expert-certification.readthedocs.io']
theme:
  name: readthedocs
nav:
  - Home: index.md

  - 'FIWARE Experts Certification': 'experts.md'
  - 'Definitions and Summary': 'summary.md'
  - 'Appendix: Sample Questions': 'appendix.md'
